apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-task
  labels: 
    app: workshop
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop
      component: frontend
  template:
    metadata:
      labels:
        app: workshop
        component: frontend
    spec:
      containers:
        - name: frontend
          image: nischit007/workshop-frontend:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: BACKEND_URL
              value: http://task-manager-service.default.svc.cluster.local
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '528Mi'              
      